[pytest]
# Thư mục chứa test
testpaths = tests

# Cho phép import "from pages.so_do_page import ..." từ trong tests/
pythonpath = tests

# Tùy chọn mặc định mỗi lần chạy pytest:
#   -v        : in chi tiết từng test
#   --headed  : mở trình duyệt hiện hình (bỏ đi nếu muốn chạy ẩn)
#   --browser : chọn trình duyệt
addopts = -v --headed --browser chromium
